insert into items values ("Riceland American Jazmine Rice", 7.21);
insert into items values ("Caress Velvet Bliss Ultra Silkening Beauty Bar - 6 Ct", 19.31);
insert into items values ("Earth's Best Organic Fruit Yogurt Smoothie Mixed Berry", 6.51);
insert into items values ("Boar's Head Sliced White American Cheese - 120 Ct", 5.64);
insert into items values ("Back To Nature Gluten Free White Cheddar Rice Thin Crackers", 8.74);
insert into items values ("Sally Hansen Nail Color Magnetic 903 Silver Elements", 2.69);
insert into items values ("Twinings Of London Classics Lady Grey Tea - 20 Ct", 8.3);
insert into items values ("Lea & Perrins Marinade In-a-bag Cracked Peppercorn", 30.05);
insert into items values ("Van De Kamp's Fillets Beer Battered - 10 Ct", 15.65);
insert into items values ("Ahold Cocoa Almonds", 10.38);
insert into items values ("Honest Tea Peach White Tea", 9.77);
insert into items values ("Mueller Sport Care Basic Support Level Medium Elastic Knee Support", 8.44);
insert into items values ("Garnier Nutritioniste Moisture Rescue Fresh Cleansing Foam", 21.55);
insert into items values ("Pamprin Maximum Strength Multi-symptom Menstrual Pain Relief", 20.81);
insert into items values ("Suave Naturals Moisturizing Body Wash Creamy Tropical Coconut", 14.52);
insert into items values ("Burt's Bees Daily Moisturizing Cream Sensitive", 22.51);
insert into items values ("Ducal Refried Red Beans", 9.66);
insert into items values ("Scotch Removable Clear Mounting Squares - 35 Ct", 23.68);
insert into items values ("Careone Family Comb Set - 8 Ct", 0.37);
insert into items values ("Plums Black", 5.72);
insert into items values ("Doctor's Best Best Curcumin C3 Complex 1000mg Tablets - 120 Ct", 9.12);
insert into items values ("Betty Crocker Twin Pack Real Potatoes Scalloped 2 Pouches For 2 Meals - 2 Pk", 8.16);
insert into items values ("Reese Mandarin Oranges Segments In Light Syrup", 16.94);
insert into items values ("Smart Living Charcoal Lighter Fluid", 20.95);
insert into items values ("Hood Latte Iced Coffee Drink Vanilla Latte", 4.39);
insert into items values ("Triaminic Syrup Night Time Cold & Cough Grape 4oz", 4.86);
insert into items values ("Morton Kosher Salt Coarse", 12.81);
insert into items values ("Guava", 9.29);
insert into items values ("Heinz Tomato Ketchup - 2 Ct", 10.32);
insert into items values ("Petmate Booda Bones Steak, Bacon & Chicken Flavors - 9 Ct", 15.04);
insert into items values ("Zhena's Gypsy Tea Herbal Red Tea Sachets Fire Light Chai - 22 Ct", 10.13);
insert into items values ("Barefoot Pinot Grigio  187", 1.99);
insert into items values ("Tomy The First Years Gumdrop Orthodontic Pacifiers 6m+ - 2ct", 21.78);
insert into items values ("Halls Menthol Cough Suppresant/oral Anesthetic Drops Honey-lemon - 30 Ct", 0.79);
insert into items values ("Nature's Way Forskohlii - 60 Ct", 7.27);
insert into items values ("Rice Bran Gluten Free Dinner Rolls Plain", 10.94);
insert into items values ("Nakano Seasoned Rice Vinegar Original", 23.54);
insert into items values ("Sundown Naturals Essential Electrolytes Tropical Punch, Watermelon And Fruit Punch Gummies - 60 Ct", 19.72);
insert into items values ("Munchies Sandwich Crackers Cheddar Cheese On Golden Toast Crackers - 8 Pk", 2.92);
insert into items values ("Amy's Light & Lean Spaghetti Italiano", 13.97);
insert into items values ("P.f. Chang's Home Menu Meal For Two Beef With Broccoli", 6.34);
insert into items values ("Mom's Best Naturals Cereal Toasted Cinnamon Squares", 12.33);
insert into items values ("Ferrara Vanilla Syrup", 9.22);
insert into items values ("Elmer's Board Mate Dual Tip Glue Pen", 12.25);
insert into items values ("Kellogg's Disney Pixar Cars 2 Cereal", 0.41);
insert into items values ("Pizza Sauce", 7.32);
insert into items values ("Bear Naked Fit Almond Crisp 100% Natural Energy Cereal", 4.81);
insert into items values ("Dove Men + Care Antiperspirant Deodorant Cool Silver", 9.25);
insert into items values ("Easy-off Oven Cleaner Lemon Scent", 10.06);
insert into items values ("Choice Organic Teas Black Tea Classic Black - 16 Ct", 5.84);
insert into items values ("Careone Lubricating Jelly", 23.41);
insert into items values ("Sacla Italia Sun Dried Pesto Sauce", 8.95);
insert into items values ("Huggies Natural Care Wipes - 3 Pk", 20.21);
insert into items values ("Serpis Green Olives Stuffed With Spicy Chorizo", 6.4);
insert into items values ("Ripken Power Shred Beef Jerky Teriyaki", 22.12);
insert into items values ("Arnold Bread Jewish Rye Everything", 11.08);
insert into items values ("Traditional Medicinals Herbal Tea Bags Just For Kids Organic Nighty Night - 18 Ct", 17.24);
insert into items values ("Perry's Ice Cream Panda Paws", 10.66);
insert into items values ("Black Swan Shiraz Merlot 1.5", 9.68);
insert into items values ("Maty's All Natural Kids 1+ Caramel Banana Taste Cough Syrup", 13.27);
insert into items values ("Kraft Anything Dressing Honey Mustard", 5.29);
insert into items values ("Eight O'clock Coffee Dark Italian Roast Ground", 14.34);
insert into items values ("Ahold  Honey Mustard", 11.67);
insert into items values ("Enzymatic Therapy  Acidophilus Pearls Active Cultures Dietary Supplement - 30 Ct", 0.35);
insert into items values ("Ahold Complete Buttermilk Pancake & Waffle Mix", 23.85);
insert into items values ("Salsa Habanero", 13.08);
insert into items values ("Say-it Sandwich & Snack Bags- 60 Pk", 5.46);
insert into items values ("Hillshire Farm Deli Select Smoked Ham With Water Added Ultra Thin", 12.57);
insert into items values ("Nestle Coffee-mate Fat Free Hazelnut Flavor Coffee Creamer", 3.09);
insert into items values ("Careone Cotton Swabs", 4.4);
insert into items values ("1-day Vaginal Antifungal Prefilled Applicator 1-dose Treatment", 16.4);
insert into items values ("Preparation H Hemorrhoidal Ointment", 13.38);
insert into items values ("Roth Kase Mini Cheeseboard Kit Havarti, Gruyere & Pepper Jack - 3 Ct", 19.14);
insert into items values ("Firm Grip Disposable Nitrile Gloves - 10 Gloves", 23.9);
insert into items values ("Downy Ultra Infusions Orchid Allure Fabric Softener - 48 Loads", 0.93);
insert into items values ("Hostess Mini Muffins Chocolate Chip - 20 Ct", 17.81);
insert into items values ("Gerber Graduates For Toddlers Lil' Meals Pasta Shells & Cheese", 2.33);
insert into items values ("Powerbar Protein Plus High Protein Bar Vanilla Yogurt", 8.2);
insert into items values ("Every Man Jack Shave Cream", 7.42);
insert into items values ("Ahold Premium Paper Towels Giant Rolls - 8 Ct", 7.2);
insert into items values ("Piacci Parmesan Nuggets", 10.52);
insert into items values ("Organix Smoothing Shea Butter Conditioner", 3.83);
insert into items values ("Dr. Scholl's For Her Rub Relief Strips", 13.25);
insert into items values ("Guida's Whole Milk", 2.63);
insert into items values ("Hime Wasabi Powdered Sushi", 19.98);
insert into items values ("Boneless Pork Shoulder Roast", 13.1);
insert into items values ("Boneless Pork Shoulder Roast", 3.16);
insert into items values ("Ahold Simply Enjoy Gourmet Spread Smoky Fig & Roasted Garlic", 14.43);
insert into items values ("Cuisinart Citrus Juicer Pulp Control", 29.05);
insert into items values ("Velveeta Cheese", 2.44);
insert into items values ("Lotrimin Ultra Antifungal Athlete's Foot Cream", 12.17);
insert into items values ("Pasta Lensi Gigli #253", 14.28);
insert into items values ("Cherrybrook Kitchen D.w. Sugar Cookie Mix", 3.25);
insert into items values ("Herb Pharm Black Elderberry Herbal Glycerite Extract", 10.48);
insert into items values ("Gold Bond Medicated Cornstarch Plus Baby Powder", 1.27);
insert into items values ("General Mills Sweet 'n Salty Honey Nut Chex Mix", 6.68);
insert into items values ("Udi's Soft N' Chewy Granola Bars Chocolate Chip - 5 Ct", 5.11);
insert into items values ("Smoked Pork Hocks - 4 Ct", 15.42);
insert into items values ("Kelapo Extra Virgin Coconut Oil Baking Sticks", 0.16);
insert into items values ("Margaret Holmes Peanut Patch Green Boiled Peanuts Hot & Spicy", 0.68);
insert into items values ("Kraft Velveeta Shells & Cheese 2% Milk", 12.12);
insert into items values ("Sylvania Daylight 75 Watt Indoor Light Bulb", 5.22);
insert into items values ("Sushi Chef Wakame Soup Mix Traditional Japanese Style", 22.01);
insert into items values ("Campbell's Homestyle Soup Italian-style Wedding", 13.51);
insert into items values ("Sapore Sensuale Cake Toasted Almond", 20.7);
insert into items values ("Goody Ouchless No Metal Elastics - 29 Ct", 5.19);
insert into items values ("Ahold Cooked Shrimp Large Tail-on", 12.69);
insert into items values ("Smart Living 10.5in X 8in", 5.92);
insert into items values ("3 Subject Notebook College Ruled", 0.16);
insert into items values ("Playtex Plastic Tampons Gentle Glide 360 Multi-pack Regular/super Fresh Scent - 18 Ct", 2.88);
insert into items values ("Hershey's Caramel Syrup", 5.47);
insert into items values ("Windex Original Glass & Surface Wipes - 28 Pk", 4.42);
insert into items values ("Olay Total Effects 7-in-1 Tone Correcting Eye Treatment 0.5 Fl Oz", 7.17);
insert into items values ("Alberto Vo5 Normal Balancing Shampoo", 12.93);
insert into items values ("Milani Total Lash Cover Mascara 105 Black", 24.13);
insert into items values ("Sylvia's Restaurant Specially-seasoned Field Peas With Snaps", 22.92);
insert into items values ("Nabisco Wheat Thins Snacks", 0.18);
insert into items values ("Careone Whitening Toothbrush Soft", 10.91);
insert into items values ("Vaseline Spray & Go Moisturizer Total Moisture", 17.39);
insert into items values ("Nature Made Fish Oil 1200mg Omega-3 360mg Liquid Softgels Lemon Flavor - 60 Ct", 4.54);
insert into items values ("Belluci Extra Virgin Olive Oil 100% Italian", 4.21);
insert into items values ("Ruffles Sour Cream & Onion Potato Chips", 2.05);
insert into items values ("Turkey Hill Premium Ice Cream Party Cake", 9.49);
insert into items values ("Tums Freshers Antacid Spearmint - 2 Pk", 6.21);
insert into items values ("Manishchewitz Gluten Free Wide Egg Noodles", 5.18);
insert into items values ("Gillette Fusion Proglide Cartridges - 8 Ct", 9.54);
insert into items values ("Bakery Pistachio Muffin - 4 Ct", 3.51);
insert into items values ("Frigo Cheese Heads 100% Natural String Cheese Light - 12 Ct", 30.24);
insert into items values ("Similac Advance Infant Formula With Iron Milk-based/ready To Feed - 6 Ct", 24.92);
insert into items values ("Rice A Roni Chicken Flavor Lower Sodium Rice", 10.25);
insert into items values ("Oberweis Dairy Raspberry Lemonade", 21.71);
insert into items values ("Companion Dog Biscuits Senior", 2.16);
insert into items values ("Coco Lite Multigrain Pop Cakes Whole Wheat", 1.73);
insert into items values ("Nestle The Original Coffee Mate", 13.3);
insert into items values ("Sweetleaf Natural Stevia Sweetener Packets - 70 Ct", 6.95);
insert into items values ("Pamela's Chocolate Cake Mix", 6.77);
insert into items values ("Designer Gift Bag Glitterwrap", 6.91);
insert into items values ("Ahold 5 Cheese Pizza Ready To Bake", 6.51);
insert into items values ("Rice Bran Gluten Free Mini Baguette", 18.78);
insert into items values ("Cracker Jack Popcorn Butter Toffee", 7.84);
insert into items values ("Swingline Standard Desk Stapler Bonus Pack!", 13.89);
insert into items values ("Pork Chops Bone-in Center Cut", 24.74);
insert into items values ("Pork Chops Bone-in Center Cut", 15.29);
insert into items values ("Snack Pack Tapioca Pudding - 4 Pk", 19.55);
insert into items values ("Pure Power Easy Grip Scrub Brush", 8.12);
insert into items values ("Cocktail Rx Frozen Cocktails Blue Hawaiian", 14.75);
insert into items values ("Anagram Foil Balloon 18in Happy Birthday Smiles", 7.05);
insert into items values ("Shelton's Turkey Burgers - 3 Ct", 19.39);
insert into items values ("Buckler Non-alcoholic Malt Beverage - 6 Ct", 0.38);
insert into items values ("Cento All Purpose Crushed Tomatoes", 5.06);
insert into items values ("Careone Vitamin B12 500mcg Tablets - 100 Ct", 12.83);
insert into items values ("Earth Balance Natural Peanut Butter And Flaxseed Creamy", 0.45);
insert into items values ("Looza Mango Juice Drink", 5.11);
insert into items values ("Campbell's Go Soup Coconut Curry With Chicken & Shitake Mushrooms", 10.91);
insert into items values ("Sweet Baby Ray's Barbecue Sauce", 18.05);
insert into items values ("Renuzit Gel Air Freshener Original", 4.55);
insert into items values ("Uncle Ben's Roasted Garlic Ready Whole Grain Rice Medley", 4.37);
insert into items values ("Howe Gummi Sour Brites", 7.75);
insert into items values ("Nabisco Ritz Bits Cheese Cracker Sandwiches", 20.93);
insert into items values ("Alessi Balsamic Reduction Traditional Balsamic", 0.52);
insert into items values ("Allegra Allergy 12 Hour Relief Tablets - 12 Ct", 9.25);
insert into items values ("Reynolds Staybrite Baking Cups Flowers - 36 Ct", 9.48);
insert into items values ("Mccormick Grill Mates Brown Sugar Bourbon Marinade", 3.28);
insert into items values ("Ahold Cocoa Magic Cereal", 21.59);
insert into items values ("Cocktail Rx Frozen Cocktail Cosmopolitan", 16.49);
insert into items values ("Earth Balance Natural Buttery Spread Soy Free", 9.58);
insert into items values ("T.g.i Friday's Poppers Cream Cheese Stuffed Jalapenos", 6.68);
insert into items values ("Instant Krazy Glue - 4 Ct", 19.69);
insert into items values ("Pepperidge Farm Puff Pastry Turnovers Apple - 4 Ct", 10.81);
insert into items values ("Campbell's Soup On The Go Chicken & Star Shaped Pasta Soup", 15.08);
insert into items values ("Hi-c Boppin' Strawberry Fruit Juice Boxes- 10 Pk", 6.36);
insert into items values ("Werther's Original Sugar Free Hard Candies", 13.87);
insert into items values ("Cesar Canine Cuisine Filet Mignon Flavor", 12.22);
insert into items values ("Freshpet Chilly Wags Natural Vanilla Flavor Frozen Treats For Dogs - 4 Ct", 12.19);
insert into items values ("Boston Market Spaghetti With Meatballs", 12.14);
insert into items values ("Osem Soup & Seasoning Mix Consomme", 13.0);
insert into items values ("Smart Living Assorted Binder Clips - 10 Ct", 10.39);
insert into items values ("Golden Krust Jamaican Style Spicy Beef Patties - 2 Ct", 11.25);
insert into items values ("Eden Organic Shelled & Dry Roasted Pistachios", 7.74);
insert into items values ("Mccormick Grill Mates Mesquite Marinade", 7.99);
insert into items values ("Urban Accents Fisherman's Wharf Seafood Seasoning", 18.35);
insert into items values ("Tastykake Cream Filled Koffee Kake Cupcakes Family Pack - 12 Ct", 9.05);
insert into items values ("Kikkoman Soy Sauce", 0.93);
insert into items values ("International Delight Coffee Creamer Irish Cream", 15.6);
insert into items values ("Ahold Honey Ham - Water Added", 7.82);
insert into items values ("Ahold Fitness Grape Creatine", 5.95);
insert into items values ("Premier Protein Crisp Crunchy Protein Bar Peanut Butter Caramel - 6 Ct", 11.7);
insert into items values ("Whitmor Stacking Shelf White Grid Medium", 13.79);
insert into items values ("Fruit Gushers Fruit Flavored Snacks Value Pack - 12 Ct", 16.42);
insert into items values ("Suave Naturals Everlasting Sunshine Shampoo", 10.2);
insert into items values ("Hot Pockets Sandwiches Cheeseburgers - 4 Ct", 1.1);
insert into items values ("Turkey Hill Premium Ice Cream Getrude Hawk Chocolates Box Of Chocolates", 6.36);
insert into items values ("Currant Affair Black Currant Cranberry Juice", 3.57);
insert into items values ("Spectrum Essentials Prenatal Dha Softgels - 60 Ct", 10.37);
insert into items values ("Lundberg Risotto Butternut Squash", 6.81);
insert into items values ("Twin Dragon Cookies Almond Chinese Style", 9.18);
insert into items values ("Gerber Multigrain Cereal", 9.92);
insert into items values ("Pure Protein Soft Baked Protein Bar Double Double Chocolate Vanilla Crunch", 14.34);
insert into items values ("Burt's Bees Green Tea & Lemongrass Hand Soap", 11.85);
insert into items values ("Rice Select Royal Blend Whole Grain", 9.45);
insert into items values ("Weight Watchers Smart Ones Smart Delights Strawberry Shortcake - 4 Ct", 14.31);