insert into deliveryvehicles values ("3M79LJ6")
insert into deliveryvehicles values ("DJEL5 8")
insert into deliveryvehicles values ("BLC5FD1")
insert into deliveryvehicles values ("G2 N4A9")
insert into deliveryvehicles values ("M8ALHE ")
insert into deliveryvehicles values ("MHG1B89")
insert into deliveryvehicles values ("5B F73N")
insert into deliveryvehicles values ("J36LD97")
insert into deliveryvehicles values ("G6EB9J2")
insert into deliveryvehicles values ("F62HI89")
insert into deliveryvehicles values ("L64E39A")
insert into deliveryvehicles values ("9EH5IL1")
insert into deliveryvehicles values ("3BD8JHK")
insert into deliveryvehicles values ("IH85NCA")
insert into deliveryvehicles values ("578421H")
insert into deliveryvehicles values ("2FBML87")
insert into deliveryvehicles values ("8BCEH14")
insert into deliveryvehicles values ("GJCD6 E")
insert into deliveryvehicles values ("FM62JG3")
insert into deliveryvehicles values ("BEG67 8")
insert into deliveryvehicles values ("9LFDJ3A")
insert into deliveryvehicles values ("I7JBKN6")
insert into deliveryvehicles values ("5N941BG")
insert into deliveryvehicles values (" 34BJMD")
insert into deliveryvehicles values ("HCFE634")
